[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://broker.hivemq.com:1883"]
  topics = ["bierwaage/data"]
  client_id = "telegraf-bierwaage-01"
  data_format = "json"
  json_string_fields = ["datetime_date", "datetime_time"]

[[outputs.http]]
  url = "http://ingest:8000/ingest"
  data_format = "json"
  method = "POST"
